settings:
  lib_name: a21o_sky130_tt_1v80_025C
  results_dir: output
  temperature: 25

  named_nodes:
    primary_power:
      name: VDD
      voltage: 1.8

    primary_ground:
      name: VSS
      voltage: 0.0

cells:
  a21o:
    netlist: "cells/a21o_pex.spice"

    area: 3.7536

    models:
      - "config/mc_switches.spice"
      - "sky130A/libs.tech/ngspice/sky130.lib.spice tt"

    data_slews: [0.01, 0.05, 0.1, 0.2]
    loads: [0.001, 0.005, 0.01, 0.05]

    functions:
      - "X= (A1 * A2) + B1"
